package com.thinkerwolf.blog.article.model;

import java.util.Date;

public class Article {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.id
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.member_id
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    private String memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.title
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.sub_title
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    private String subTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.pic
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    private String pic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.create_time
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.browse_num
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    private Integer browseNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.id
     *
     * @return the value of article.id
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.id
     *
     * @param id the value for article.id
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.member_id
     *
     * @return the value of article.member_id
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.member_id
     *
     * @param memberId the value for article.member_id
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    public void setMemberId(String memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.title
     *
     * @return the value of article.title
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.title
     *
     * @param title the value for article.title
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.sub_title
     *
     * @return the value of article.sub_title
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    public String getSubTitle() {
        return subTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.sub_title
     *
     * @param subTitle the value for article.sub_title
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    public void setSubTitle(String subTitle) {
        this.subTitle = subTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.pic
     *
     * @return the value of article.pic
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.pic
     *
     * @param pic the value for article.pic
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    public void setPic(String pic) {
        this.pic = pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.create_time
     *
     * @return the value of article.create_time
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.create_time
     *
     * @param createTime the value for article.create_time
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.browse_num
     *
     * @return the value of article.browse_num
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    public Integer getBrowseNum() {
        return browseNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.browse_num
     *
     * @param browseNum the value for article.browse_num
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    public void setBrowseNum(Integer browseNum) {
        this.browseNum = browseNum;
    }
}