package com.thinkerwolf.blog.article.model;

public class ArticleTopic {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_topic.id
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_topic.article_id
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    private String articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_topic.topic_id
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    private String topicId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_topic.id
     *
     * @return the value of article_topic.id
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_topic.id
     *
     * @param id the value for article_topic.id
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_topic.article_id
     *
     * @return the value of article_topic.article_id
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    public String getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_topic.article_id
     *
     * @param articleId the value for article_topic.article_id
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    public void setArticleId(String articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_topic.topic_id
     *
     * @return the value of article_topic.topic_id
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    public String getTopicId() {
        return topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_topic.topic_id
     *
     * @param topicId the value for article_topic.topic_id
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    public void setTopicId(String topicId) {
        this.topicId = topicId;
    }
}