package com.thinkerwolf.blog.article.model;

import java.util.Date;

public class ArticleComment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_comment.id
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_comment.member_id
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    private String memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_comment.article_id
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    private String articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_comment.commont_id
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    private String commontId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_comment.create_time
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_comment.approval
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    private Integer approval;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_comment.oppose
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    private Integer oppose;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_comment.content
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_comment.id
     *
     * @return the value of article_comment.id
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_comment.id
     *
     * @param id the value for article_comment.id
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_comment.member_id
     *
     * @return the value of article_comment.member_id
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_comment.member_id
     *
     * @param memberId the value for article_comment.member_id
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    public void setMemberId(String memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_comment.article_id
     *
     * @return the value of article_comment.article_id
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    public String getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_comment.article_id
     *
     * @param articleId the value for article_comment.article_id
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    public void setArticleId(String articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_comment.commont_id
     *
     * @return the value of article_comment.commont_id
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    public String getCommontId() {
        return commontId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_comment.commont_id
     *
     * @param commontId the value for article_comment.commont_id
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    public void setCommontId(String commontId) {
        this.commontId = commontId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_comment.create_time
     *
     * @return the value of article_comment.create_time
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_comment.create_time
     *
     * @param createTime the value for article_comment.create_time
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_comment.approval
     *
     * @return the value of article_comment.approval
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    public Integer getApproval() {
        return approval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_comment.approval
     *
     * @param approval the value for article_comment.approval
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    public void setApproval(Integer approval) {
        this.approval = approval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_comment.oppose
     *
     * @return the value of article_comment.oppose
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    public Integer getOppose() {
        return oppose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_comment.oppose
     *
     * @param oppose the value for article_comment.oppose
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    public void setOppose(Integer oppose) {
        this.oppose = oppose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_comment.content
     *
     * @return the value of article_comment.content
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_comment.content
     *
     * @param content the value for article_comment.content
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    public void setContent(String content) {
        this.content = content;
    }
}