package com.thinkerwolf.blogmg.menu.mapper;

import com.thinkerwolf.blogmg.menu.model.Menu;
import com.thinkerwolf.blogmg.menu.model.MenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MenuMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table menu
	 * @mbg.generated  Mon Apr 08 17:41:02 CST 2019
	 */
	long countByExample(MenuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table menu
	 * @mbg.generated  Mon Apr 08 17:41:02 CST 2019
	 */
	int deleteByExample(MenuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table menu
	 * @mbg.generated  Mon Apr 08 17:41:02 CST 2019
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table menu
	 * @mbg.generated  Mon Apr 08 17:41:02 CST 2019
	 */
	int insert(Menu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table menu
	 * @mbg.generated  Mon Apr 08 17:41:02 CST 2019
	 */
	int insertSelective(Menu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table menu
	 * @mbg.generated  Mon Apr 08 17:41:02 CST 2019
	 */
	List<Menu> selectByExample(MenuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table menu
	 * @mbg.generated  Mon Apr 08 17:41:02 CST 2019
	 */
	Menu selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table menu
	 * @mbg.generated  Mon Apr 08 17:41:02 CST 2019
	 */
	int updateByExampleSelective(@Param("record") Menu record, @Param("example") MenuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table menu
	 * @mbg.generated  Mon Apr 08 17:41:02 CST 2019
	 */
	int updateByExample(@Param("record") Menu record, @Param("example") MenuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table menu
	 * @mbg.generated  Mon Apr 08 17:41:02 CST 2019
	 */
	int updateByPrimaryKeySelective(Menu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table menu
	 * @mbg.generated  Mon Apr 08 17:41:02 CST 2019
	 */
	int updateByPrimaryKey(Menu record);
}