package com.thinkerwolf.blogmg.user.model;

import java.util.Date;

public class Permission {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column permission.id
	 * @mbg.generated  Mon Apr 08 17:41:02 CST 2019
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column permission.name
	 * @mbg.generated  Mon Apr 08 17:41:02 CST 2019
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column permission.create_time
	 * @mbg.generated  Mon Apr 08 17:41:02 CST 2019
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column permission.update_time
	 * @mbg.generated  Mon Apr 08 17:41:02 CST 2019
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column permission.rules
	 * @mbg.generated  Mon Apr 08 17:41:02 CST 2019
	 */
	private String rules;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column permission.id
	 * @return  the value of permission.id
	 * @mbg.generated  Mon Apr 08 17:41:02 CST 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column permission.id
	 * @param id  the value for permission.id
	 * @mbg.generated  Mon Apr 08 17:41:02 CST 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column permission.name
	 * @return  the value of permission.name
	 * @mbg.generated  Mon Apr 08 17:41:02 CST 2019
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column permission.name
	 * @param name  the value for permission.name
	 * @mbg.generated  Mon Apr 08 17:41:02 CST 2019
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column permission.create_time
	 * @return  the value of permission.create_time
	 * @mbg.generated  Mon Apr 08 17:41:02 CST 2019
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column permission.create_time
	 * @param createTime  the value for permission.create_time
	 * @mbg.generated  Mon Apr 08 17:41:02 CST 2019
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column permission.update_time
	 * @return  the value of permission.update_time
	 * @mbg.generated  Mon Apr 08 17:41:02 CST 2019
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column permission.update_time
	 * @param updateTime  the value for permission.update_time
	 * @mbg.generated  Mon Apr 08 17:41:02 CST 2019
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column permission.rules
	 * @return  the value of permission.rules
	 * @mbg.generated  Mon Apr 08 17:41:02 CST 2019
	 */
	public String getRules() {
		return rules;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column permission.rules
	 * @param rules  the value for permission.rules
	 * @mbg.generated  Mon Apr 08 17:41:02 CST 2019
	 */
	public void setRules(String rules) {
		this.rules = rules;
	}
}