package com.thinkerwolf.blogmg.menu.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class Menu {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column menu.id
	 * @mbg.generated  Mon Apr 08 17:41:02 CST 2019
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column menu.parent_id
	 * @mbg.generated  Mon Apr 08 17:41:02 CST 2019
	 */
	private Integer parentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column menu.code
	 * @mbg.generated  Mon Apr 08 17:41:02 CST 2019
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column menu.name
	 * @mbg.generated  Mon Apr 08 17:41:02 CST 2019
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column menu.seq
	 * @mbg.generated  Mon Apr 08 17:41:02 CST 2019
	 */
	private Integer seq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column menu.create_time
	 * @mbg.generated  Mon Apr 08 17:41:02 CST 2019
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column menu.url
	 * @mbg.generated  Mon Apr 08 17:41:02 CST 2019
	 */
	private String url;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column menu.id
	 * @return  the value of menu.id
	 * @mbg.generated  Mon Apr 08 17:41:02 CST 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column menu.id
	 * @param id  the value for menu.id
	 * @mbg.generated  Mon Apr 08 17:41:02 CST 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column menu.parent_id
	 * @return  the value of menu.parent_id
	 * @mbg.generated  Mon Apr 08 17:41:02 CST 2019
	 */
	public Integer getParentId() {
		return parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column menu.parent_id
	 * @param parentId  the value for menu.parent_id
	 * @mbg.generated  Mon Apr 08 17:41:02 CST 2019
	 */
	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column menu.code
	 * @return  the value of menu.code
	 * @mbg.generated  Mon Apr 08 17:41:02 CST 2019
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column menu.code
	 * @param code  the value for menu.code
	 * @mbg.generated  Mon Apr 08 17:41:02 CST 2019
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column menu.name
	 * @return  the value of menu.name
	 * @mbg.generated  Mon Apr 08 17:41:02 CST 2019
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column menu.name
	 * @param name  the value for menu.name
	 * @mbg.generated  Mon Apr 08 17:41:02 CST 2019
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column menu.seq
	 * @return  the value of menu.seq
	 * @mbg.generated  Mon Apr 08 17:41:02 CST 2019
	 */
	public Integer getSeq() {
		return seq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column menu.seq
	 * @param seq  the value for menu.seq
	 * @mbg.generated  Mon Apr 08 17:41:02 CST 2019
	 */
	public void setSeq(Integer seq) {
		this.seq = seq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column menu.create_time
	 * @return  the value of menu.create_time
	 * @mbg.generated  Mon Apr 08 17:41:02 CST 2019
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column menu.create_time
	 * @param createTime  the value for menu.create_time
	 * @mbg.generated  Mon Apr 08 17:41:02 CST 2019
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column menu.url
	 * @return  the value of menu.url
	 * @mbg.generated  Mon Apr 08 17:41:02 CST 2019
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column menu.url
	 * @param url  the value for menu.url
	 * @mbg.generated  Mon Apr 08 17:41:02 CST 2019
	 */
	public void setUrl(String url) {
		this.url = url;
	}

	private List<Menu> children = new ArrayList<>();

	public List<Menu> getChildren() {
		return children;
	}
	
}