package com.thinkerwolf.blog.article.mapper;

import com.thinkerwolf.blog.article.model.Article;
import com.thinkerwolf.blog.article.model.ArticleCondition;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArticleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    long countByCondition(ArticleCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    int deleteByCondition(ArticleCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    int insert(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    int insertSelective(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    List<Article> selectByCondition(ArticleCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    Article selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    int updateByConditionSelective(@Param("record") Article record, @Param("example") ArticleCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    int updateByCondition(@Param("record") Article record, @Param("example") ArticleCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    int updateByPrimaryKeySelective(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    int updateByPrimaryKey(Article record);
}