package com.thinkerwolf.blog.article.mapper;

import com.thinkerwolf.blog.article.model.ArticleComment;
import com.thinkerwolf.blog.article.model.ArticleCommentCondition;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArticleCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_comment
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    long countByCondition(ArticleCommentCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_comment
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    int deleteByCondition(ArticleCommentCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_comment
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_comment
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    int insert(ArticleComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_comment
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    int insertSelective(ArticleComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_comment
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    List<ArticleComment> selectByCondition(ArticleCommentCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_comment
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    ArticleComment selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_comment
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    int updateByConditionSelective(@Param("record") ArticleComment record, @Param("example") ArticleCommentCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_comment
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    int updateByCondition(@Param("record") ArticleComment record, @Param("example") ArticleCommentCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_comment
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    int updateByPrimaryKeySelective(ArticleComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_comment
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    int updateByPrimaryKey(ArticleComment record);
}