package com.thinkerwolf.blog.article.mapper;

import com.thinkerwolf.blog.article.model.ArticleTopic;
import com.thinkerwolf.blog.article.model.ArticleTopicCondition;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArticleTopicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_topic
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    long countByCondition(ArticleTopicCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_topic
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    int deleteByCondition(ArticleTopicCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_topic
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_topic
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    int insert(ArticleTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_topic
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    int insertSelective(ArticleTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_topic
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    List<ArticleTopic> selectByCondition(ArticleTopicCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_topic
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    ArticleTopic selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_topic
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    int updateByConditionSelective(@Param("record") ArticleTopic record, @Param("example") ArticleTopicCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_topic
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    int updateByCondition(@Param("record") ArticleTopic record, @Param("example") ArticleTopicCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_topic
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    int updateByPrimaryKeySelective(ArticleTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_topic
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    int updateByPrimaryKey(ArticleTopic record);
}