package com.thinkerwolf.blogmg.user.mapper;

import com.thinkerwolf.blogmg.user.model.Permission;
import com.thinkerwolf.blogmg.user.model.PermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PermissionMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table permission
	 * @mbg.generated  Mon Apr 08 17:41:02 CST 2019
	 */
	long countByExample(PermissionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table permission
	 * @mbg.generated  Mon Apr 08 17:41:02 CST 2019
	 */
	int deleteByExample(PermissionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table permission
	 * @mbg.generated  Mon Apr 08 17:41:02 CST 2019
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table permission
	 * @mbg.generated  Mon Apr 08 17:41:02 CST 2019
	 */
	int insert(Permission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table permission
	 * @mbg.generated  Mon Apr 08 17:41:02 CST 2019
	 */
	int insertSelective(Permission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table permission
	 * @mbg.generated  Mon Apr 08 17:41:02 CST 2019
	 */
	List<Permission> selectByExample(PermissionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table permission
	 * @mbg.generated  Mon Apr 08 17:41:02 CST 2019
	 */
	Permission selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table permission
	 * @mbg.generated  Mon Apr 08 17:41:02 CST 2019
	 */
	int updateByExampleSelective(@Param("record") Permission record, @Param("example") PermissionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table permission
	 * @mbg.generated  Mon Apr 08 17:41:02 CST 2019
	 */
	int updateByExample(@Param("record") Permission record, @Param("example") PermissionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table permission
	 * @mbg.generated  Mon Apr 08 17:41:02 CST 2019
	 */
	int updateByPrimaryKeySelective(Permission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table permission
	 * @mbg.generated  Mon Apr 08 17:41:02 CST 2019
	 */
	int updateByPrimaryKey(Permission record);
	
	List<Permission> selectUserPermissions(String userId);
	
}