package com.thinkerwolf.blog.member.mapper;

import com.thinkerwolf.blog.member.model.Member;
import com.thinkerwolf.blog.member.model.MemberCondition;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    long countByCondition(MemberCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    int deleteByCondition(MemberCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    int insert(Member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    int insertSelective(Member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    List<Member> selectByCondition(MemberCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    Member selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    int updateByConditionSelective(@Param("record") Member record, @Param("example") MemberCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    int updateByCondition(@Param("record") Member record, @Param("example") MemberCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    int updateByPrimaryKeySelective(Member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbg.generated Wed Apr 10 19:13:51 CST 2019
     */
    int updateByPrimaryKey(Member record);
}