package com.blog.modal;

public class MemMember {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mem_member.ID
	 * @mbg.generated  Sat Mar 25 17:13:28 CST 2017
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mem_member.VERSION
	 * @mbg.generated  Sat Mar 25 17:13:28 CST 2017
	 */
	private Integer version;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mem_member.USERNAME
	 * @mbg.generated  Sat Mar 25 17:13:28 CST 2017
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mem_member.PHONE
	 * @mbg.generated  Sat Mar 25 17:13:28 CST 2017
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mem_member.MAIL
	 * @mbg.generated  Sat Mar 25 17:13:28 CST 2017
	 */
	private String mail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mem_member.PASSWORD
	 * @mbg.generated  Sat Mar 25 17:13:28 CST 2017
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mem_member.HEAD_PHO
	 * @mbg.generated  Sat Mar 25 17:13:28 CST 2017
	 */
	private String headPho;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mem_member.ID
	 * @return  the value of mem_member.ID
	 * @mbg.generated  Sat Mar 25 17:13:28 CST 2017
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mem_member.ID
	 * @param id  the value for mem_member.ID
	 * @mbg.generated  Sat Mar 25 17:13:28 CST 2017
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mem_member.VERSION
	 * @return  the value of mem_member.VERSION
	 * @mbg.generated  Sat Mar 25 17:13:28 CST 2017
	 */
	public Integer getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mem_member.VERSION
	 * @param version  the value for mem_member.VERSION
	 * @mbg.generated  Sat Mar 25 17:13:28 CST 2017
	 */
	public void setVersion(Integer version) {
		this.version = version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mem_member.USERNAME
	 * @return  the value of mem_member.USERNAME
	 * @mbg.generated  Sat Mar 25 17:13:28 CST 2017
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mem_member.USERNAME
	 * @param username  the value for mem_member.USERNAME
	 * @mbg.generated  Sat Mar 25 17:13:28 CST 2017
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mem_member.PHONE
	 * @return  the value of mem_member.PHONE
	 * @mbg.generated  Sat Mar 25 17:13:28 CST 2017
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mem_member.PHONE
	 * @param phone  the value for mem_member.PHONE
	 * @mbg.generated  Sat Mar 25 17:13:28 CST 2017
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mem_member.MAIL
	 * @return  the value of mem_member.MAIL
	 * @mbg.generated  Sat Mar 25 17:13:28 CST 2017
	 */
	public String getMail() {
		return mail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mem_member.MAIL
	 * @param mail  the value for mem_member.MAIL
	 * @mbg.generated  Sat Mar 25 17:13:28 CST 2017
	 */
	public void setMail(String mail) {
		this.mail = mail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mem_member.PASSWORD
	 * @return  the value of mem_member.PASSWORD
	 * @mbg.generated  Sat Mar 25 17:13:28 CST 2017
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mem_member.PASSWORD
	 * @param password  the value for mem_member.PASSWORD
	 * @mbg.generated  Sat Mar 25 17:13:28 CST 2017
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mem_member.HEAD_PHO
	 * @return  the value of mem_member.HEAD_PHO
	 * @mbg.generated  Sat Mar 25 17:13:28 CST 2017
	 */
	public String getHeadPho() {
		return headPho;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mem_member.HEAD_PHO
	 * @param headPho  the value for mem_member.HEAD_PHO
	 * @mbg.generated  Sat Mar 25 17:13:28 CST 2017
	 */
	public void setHeadPho(String headPho) {
		this.headPho = headPho;
	}
}